<?= $this->extend('admin/layouts/main') ?>

<?= $this->section('content') ?>
<?php
$draftStatus = trim((string) ($draft['status'] ?? 'DRAFT'));
$config = is_array($cartConfig ?? null) ? $cartConfig : [];
$sections = is_array($config['sections'] ?? null) ? $config['sections'] : [];
?>

<div class="page-header">
    <div class="page-block">
        <div class="row">
            <div class="col-12"><div class="page-header-title"><h2 class="mb-0"><?= esc($page['name']) ?> Yonetimi</h2></div></div>
            <div class="col-12"><ul class="breadcrumb"><li class="breadcrumb-item"><a href="<?= site_url('admin/dashboard') ?>">Yonetim</a></li><li class="breadcrumb-item"><a href="<?= site_url('admin/pages') ?>">Sayfa Yonetimi</a></li><li class="breadcrumb-item" aria-current="page">Cart Builder</li></ul></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card border-0 shadow-sm mb-4">
            <div class="card-body d-flex flex-wrap justify-content-between align-items-center gap-3">
                <div>
                    <div class="d-flex flex-wrap gap-2 mb-2"><span class="badge bg-light-primary"><?= esc($draftStatus) ?></span><span class="badge bg-light-secondary"><?= esc($page['code']) ?></span><span class="badge bg-light-success">Kontrollu Cart Sablonu</span></div>
                    <h4 class="mb-1">Cart Sayfa Sistemi</h4>
                    <p class="text-muted mb-0"><?= esc((string) ($builderPolicy['message'] ?? 'Cart sayfasi tam serbest builder yerine kontrollu section mantigiyla yonetilir.')) ?></p>
                </div>
                <a href="<?= site_url('admin/pages/' . $page['code'] . '/drafts') ?>" class="btn btn-outline-primary">Draftlar</a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xxl-5">
        <div class="card mb-4">
            <div class="card-header"><h5 class="mb-1">Section Yonetimi</h5><p class="text-muted mb-0">Cart is mantigini degistirmeden metinleri, gorunurlugu ve sirayi yonetin.</p></div>
            <div class="card-body">
                <?php if (session()->getFlashdata('error')): ?><div class="alert alert-danger"><?= esc(session()->getFlashdata('error')) ?></div><?php endif; ?>
                <?php if (session()->getFlashdata('success')): ?><div class="alert alert-success"><?= esc(session()->getFlashdata('success')) ?></div><?php endif; ?>
                <div class="alert alert-light border mb-4"><div class="fw-semibold mb-1"><?= esc((string) ($builderPolicy['title'] ?? 'Cart policy')) ?></div><div class="small text-muted mb-0"><?= esc((string) ($builderPolicy['message'] ?? 'Bu sayfa kontrollu section ayarlariyla yonetilir.')) ?></div></div>

                <form action="<?= site_url('admin/pages/cart-builder/update') ?>" method="post">
                    <?= csrf_field() ?>
                    <input type="hidden" name="page_code" value="<?= esc($page['code']) ?>">
                    <input type="hidden" name="version_id" value="<?= esc($draft['id']) ?>">

                    <div class="accordion" id="cartSectionsAccordion">
                        <div class="accordion-item border rounded mb-3"><h2 class="accordion-header"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#cartTopArea">Sayfa Ust Alani</button></h2><div id="cartTopArea" class="accordion-collapse collapse show" data-bs-parent="#cartSectionsAccordion"><div class="accordion-body"><div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">Bolum Durumu</label><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="section_sayfa_ust_alani_active" value="1" <?= old('section_sayfa_ust_alani_active', ! empty($sections['sayfa_ust_alani']['active']) ? '1' : '') ? 'checked' : '' ?>><label class="form-check-label">Aktif</label></div></div><div class="col-md-6"><label class="form-label">Sira</label><input type="number" min="1" name="section_sayfa_ust_alani_order" class="form-control" value="<?= esc((string) old('section_sayfa_ust_alani_order', (string) ($sections['sayfa_ust_alani']['order'] ?? 1))) ?>"></div></div><div class="mb-3"><label class="form-label">Baslik</label><input type="text" name="sayfa_basligi" class="form-control" value="<?= esc(old('sayfa_basligi', (string) ($config['sayfa_basligi'] ?? ''))) ?>"></div><div class="mb-3"><label class="form-label">Alt Baslik</label><textarea name="sayfa_alt_basligi" rows="3" class="form-control"><?= esc(old('sayfa_alt_basligi', (string) ($config['sayfa_alt_basligi'] ?? ''))) ?></textarea></div><div class="row g-3"><div class="col-md-6"><div class="form-check"><input class="form-check-input" type="checkbox" name="breadcrumb_goster" value="1" <?= old('breadcrumb_goster', ! empty($config['breadcrumb_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Breadcrumb goster</label></div></div><div class="col-md-6"><label class="form-label">Kisa Aciklama</label><input type="text" name="kisa_aciklama" class="form-control" value="<?= esc(old('kisa_aciklama', (string) ($config['kisa_aciklama'] ?? ''))) ?>"></div></div></div></div></div>

                        <div class="accordion-item border rounded mb-3"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#cartItemsArea">Sepet Urunleri Alani</button></h2><div id="cartItemsArea" class="accordion-collapse collapse" data-bs-parent="#cartSectionsAccordion"><div class="accordion-body"><div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">Bolum Durumu</label><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="section_sepet_urunleri_alani_active" value="1" <?= old('section_sepet_urunleri_alani_active', ! empty($sections['sepet_urunleri_alani']['active']) ? '1' : '') ? 'checked' : '' ?>><label class="form-check-label">Aktif</label></div></div><div class="col-md-6"><label class="form-label">Sira</label><input type="number" min="1" name="section_sepet_urunleri_alani_order" class="form-control" value="<?= esc((string) old('section_sepet_urunleri_alani_order', (string) ($sections['sepet_urunleri_alani']['order'] ?? 2))) ?>"></div></div><div class="mb-3"><label class="form-label">Bolum Basligi</label><input type="text" name="sepet_urunleri_baslik" class="form-control" value="<?= esc(old('sepet_urunleri_baslik', (string) ($config['sepet_urunleri_baslik'] ?? ''))) ?>"></div><div class="mb-3"><label class="form-label">Aciklama Metni</label><textarea name="sepet_urunleri_aciklama" rows="3" class="form-control"><?= esc(old('sepet_urunleri_aciklama', (string) ($config['sepet_urunleri_aciklama'] ?? ''))) ?></textarea></div><div class="row g-2 mb-3"><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="urun_gorseli_goster" value="1" <?= old('urun_gorseli_goster', ! empty($config['urun_gorseli_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Urun gorselini goster</label></div></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="format_etiketi_goster" value="1" <?= old('format_etiketi_goster', ! empty($config['format_etiketi_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Format etiketini goster</label></div></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="adet_kontrolu_goster" value="1" <?= old('adet_kontrolu_goster', ! empty($config['adet_kontrolu_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Adet kontrolunu goster</label></div></div></div><div class="mb-0"><label class="form-label">Kaldir Butonu Metni</label><input type="text" name="kaldir_buton_metni" class="form-control" value="<?= esc(old('kaldir_buton_metni', (string) ($config['kaldir_buton_metni'] ?? ''))) ?>"></div></div></div></div>

                        <div class="accordion-item border rounded mb-3"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#cartPriceArea">Fiyat Guncelleme Uyari Alani</button></h2><div id="cartPriceArea" class="accordion-collapse collapse" data-bs-parent="#cartSectionsAccordion"><div class="accordion-body"><div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">Bolum Durumu</label><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="section_fiyat_guncelleme_uyari_alani_active" value="1" <?= old('section_fiyat_guncelleme_uyari_alani_active', ! empty($sections['fiyat_guncelleme_uyari_alani']['active']) ? '1' : '') ? 'checked' : '' ?>><label class="form-check-label">Aktif</label></div></div><div class="col-md-6"><label class="form-label">Sira</label><input type="number" min="1" name="section_fiyat_guncelleme_uyari_alani_order" class="form-control" value="<?= esc((string) old('section_fiyat_guncelleme_uyari_alani_order', (string) ($sections['fiyat_guncelleme_uyari_alani']['order'] ?? 3))) ?>"></div></div><div class="mb-3"><label class="form-label">Bolum Basligi</label><input type="text" name="fiyat_uyari_baslik" class="form-control" value="<?= esc(old('fiyat_uyari_baslik', (string) ($config['fiyat_uyari_baslik'] ?? ''))) ?>"></div><div class="mb-3"><label class="form-label">Aciklama Metni</label><textarea name="fiyat_uyari_aciklama" rows="3" class="form-control"><?= esc(old('fiyat_uyari_aciklama', (string) ($config['fiyat_uyari_aciklama'] ?? ''))) ?></textarea></div><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="fiyat_farki_bilgi_kutusu_goster" value="1" <?= old('fiyat_farki_bilgi_kutusu_goster', ! empty($config['fiyat_farki_bilgi_kutusu_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Fiyat farki bilgi kutusunu goster</label></div><div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">Eski Fiyat Etiketi</label><input type="text" name="eski_fiyat_etiketi" class="form-control" value="<?= esc(old('eski_fiyat_etiketi', (string) ($config['eski_fiyat_etiketi'] ?? ''))) ?>"></div><div class="col-md-6"><label class="form-label">Guncel Fiyat Etiketi</label><input type="text" name="guncel_fiyat_etiketi" class="form-control" value="<?= esc(old('guncel_fiyat_etiketi', (string) ($config['guncel_fiyat_etiketi'] ?? ''))) ?>"></div></div><div class="mb-0"><label class="form-label">Toplam Guncelleme Notu</label><textarea name="toplam_guncelleme_notu" rows="3" class="form-control"><?= esc(old('toplam_guncelleme_notu', (string) ($config['toplam_guncelleme_notu'] ?? ''))) ?></textarea></div></div></div></div>

                        <div class="accordion-item border rounded mb-3"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#cartStockArea">Stok / Uygunluk Uyari Alani</button></h2><div id="cartStockArea" class="accordion-collapse collapse" data-bs-parent="#cartSectionsAccordion"><div class="accordion-body"><div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">Bolum Durumu</label><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="section_stok_uygunluk_uyari_alani_active" value="1" <?= old('section_stok_uygunluk_uyari_alani_active', ! empty($sections['stok_uygunluk_uyari_alani']['active']) ? '1' : '') ? 'checked' : '' ?>><label class="form-check-label">Aktif</label></div></div><div class="col-md-6"><label class="form-label">Sira</label><input type="number" min="1" name="section_stok_uygunluk_uyari_alani_order" class="form-control" value="<?= esc((string) old('section_stok_uygunluk_uyari_alani_order', (string) ($sections['stok_uygunluk_uyari_alani']['order'] ?? 4))) ?>"></div></div><div class="mb-3"><label class="form-label">Bolum Basligi</label><input type="text" name="stok_uyari_baslik" class="form-control" value="<?= esc(old('stok_uyari_baslik', (string) ($config['stok_uyari_baslik'] ?? ''))) ?>"></div><div class="mb-3"><label class="form-label">Aciklama Metni</label><textarea name="stok_uyari_aciklama" rows="3" class="form-control"><?= esc(old('stok_uyari_aciklama', (string) ($config['stok_uyari_aciklama'] ?? ''))) ?></textarea></div><div class="row g-2 mb-3"><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="dusuk_stok_uyarisi_goster" value="1" <?= old('dusuk_stok_uyarisi_goster', ! empty($config['dusuk_stok_uyarisi_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Dusuk stok uyarisini goster</label></div></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="tukenme_mesaji_goster" value="1" <?= old('tukenme_mesaji_goster', ! empty($config['tukenme_mesaji_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Tukenme mesajini goster</label></div></div></div><div class="mb-3"><label class="form-label">Dusuk Stok Mesaj Sablonu</label><input type="text" name="dusuk_stok_mesaj_sablonu" class="form-control" value="<?= esc(old('dusuk_stok_mesaj_sablonu', (string) ($config['dusuk_stok_mesaj_sablonu'] ?? ''))) ?>"></div><div class="mb-0"><label class="form-label">Son Urun Mesaj Sablonu</label><input type="text" name="son_urun_mesaj_sablonu" class="form-control" value="<?= esc(old('son_urun_mesaj_sablonu', (string) ($config['son_urun_mesaj_sablonu'] ?? ''))) ?>"></div></div></div></div>

                        <div class="accordion-item border rounded mb-3"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#cartCouponArea">Kupon / Kampanya Alani</button></h2><div id="cartCouponArea" class="accordion-collapse collapse" data-bs-parent="#cartSectionsAccordion"><div class="accordion-body"><div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">Bolum Durumu</label><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="section_kupon_kampanya_alani_active" value="1" <?= old('section_kupon_kampanya_alani_active', ! empty($sections['kupon_kampanya_alani']['active']) ? '1' : '') ? 'checked' : '' ?>><label class="form-check-label">Aktif</label></div></div><div class="col-md-6"><label class="form-label">Sira</label><input type="number" min="1" name="section_kupon_kampanya_alani_order" class="form-control" value="<?= esc((string) old('section_kupon_kampanya_alani_order', (string) ($sections['kupon_kampanya_alani']['order'] ?? 5))) ?>"></div></div><div class="mb-3"><label class="form-label">Bolum Basligi</label><input type="text" name="kupon_kampanya_baslik" class="form-control" value="<?= esc(old('kupon_kampanya_baslik', (string) ($config['kupon_kampanya_baslik'] ?? ''))) ?>"></div><div class="mb-3"><label class="form-label">Aciklama Metni</label><textarea name="kupon_kampanya_aciklama" rows="3" class="form-control"><?= esc(old('kupon_kampanya_aciklama', (string) ($config['kupon_kampanya_aciklama'] ?? ''))) ?></textarea></div><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="kupon_alani_goster" value="1" <?= old('kupon_alani_goster', ! empty($config['kupon_alani_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Kupon alanini goster</label></div><div class="mb-3"><label class="form-label">Kampanya Bilgi Notu</label><textarea name="kampanya_bilgi_notu" rows="3" class="form-control"><?= esc(old('kampanya_bilgi_notu', (string) ($config['kampanya_bilgi_notu'] ?? ''))) ?></textarea></div><div class="mb-0"><label class="form-label">Ucretsiz Kargo Bilgi Notu</label><textarea name="ucretsiz_kargo_bilgi_notu" rows="3" class="form-control"><?= esc(old('ucretsiz_kargo_bilgi_notu', (string) ($config['ucretsiz_kargo_bilgi_notu'] ?? ''))) ?></textarea></div></div></div></div>

                        <div class="accordion-item border rounded mb-3"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#cartSummaryArea">Sepet Ozeti ve CTA Alani</button></h2><div id="cartSummaryArea" class="accordion-collapse collapse" data-bs-parent="#cartSectionsAccordion"><div class="accordion-body"><div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">Bolum Durumu</label><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="section_sepet_ozeti_cta_alani_active" value="1" <?= old('section_sepet_ozeti_cta_alani_active', ! empty($sections['sepet_ozeti_cta_alani']['active']) ? '1' : '') ? 'checked' : '' ?>><label class="form-check-label">Aktif</label></div></div><div class="col-md-6"><label class="form-label">Sira</label><input type="number" min="1" name="section_sepet_ozeti_cta_alani_order" class="form-control" value="<?= esc((string) old('section_sepet_ozeti_cta_alani_order', (string) ($sections['sepet_ozeti_cta_alani']['order'] ?? 6))) ?>"></div></div><div class="mb-3"><label class="form-label">Baslik</label><input type="text" name="sepet_ozeti_baslik" class="form-control" value="<?= esc(old('sepet_ozeti_baslik', (string) ($config['sepet_ozeti_baslik'] ?? ''))) ?>"></div><div class="row g-2 mb-3"><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="ara_toplam_goster" value="1" <?= old('ara_toplam_goster', ! empty($config['ara_toplam_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Ara toplami goster</label></div></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="indirim_goster" value="1" <?= old('indirim_goster', ! empty($config['indirim_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Indirimi goster</label></div></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="kargo_goster" value="1" <?= old('kargo_goster', ! empty($config['kargo_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Kargoyu goster</label></div></div></div><div class="mb-3"><label class="form-label">Genel Toplam Basligi</label><input type="text" name="genel_toplam_basligi" class="form-control" value="<?= esc(old('genel_toplam_basligi', (string) ($config['genel_toplam_basligi'] ?? ''))) ?>"></div><div class="mb-3"><label class="form-label">Odeme Sayfasina Git Buton Metni</label><input type="text" name="odeme_sayfasina_git_buton_metni" class="form-control" value="<?= esc(old('odeme_sayfasina_git_buton_metni', (string) ($config['odeme_sayfasina_git_buton_metni'] ?? ''))) ?>"></div><div class="mb-0"><label class="form-label">Guvenli Odeme Kisa Notu</label><textarea name="guvenli_odeme_kisa_notu" rows="3" class="form-control"><?= esc(old('guvenli_odeme_kisa_notu', (string) ($config['guvenli_odeme_kisa_notu'] ?? ''))) ?></textarea></div></div></div></div>

                        <div class="accordion-item border rounded mb-4"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#cartEmptyArea">Bos Sepet Alani</button></h2><div id="cartEmptyArea" class="accordion-collapse collapse" data-bs-parent="#cartSectionsAccordion"><div class="accordion-body"><div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">Bolum Durumu</label><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="section_bos_sepet_alani_active" value="1" <?= old('section_bos_sepet_alani_active', ! empty($sections['bos_sepet_alani']['active']) ? '1' : '') ? 'checked' : '' ?>><label class="form-check-label">Aktif</label></div></div><div class="col-md-6"><label class="form-label">Sira</label><input type="number" min="1" name="section_bos_sepet_alani_order" class="form-control" value="<?= esc((string) old('section_bos_sepet_alani_order', (string) ($sections['bos_sepet_alani']['order'] ?? 7))) ?>"></div></div><div class="mb-3"><label class="form-label">Baslik</label><input type="text" name="bos_sepet_baslik" class="form-control" value="<?= esc(old('bos_sepet_baslik', (string) ($config['bos_sepet_baslik'] ?? ''))) ?>"></div><div class="mb-3"><label class="form-label">Aciklama</label><textarea name="bos_sepet_aciklama" rows="3" class="form-control"><?= esc(old('bos_sepet_aciklama', (string) ($config['bos_sepet_aciklama'] ?? ''))) ?></textarea></div><div class="mb-0"><label class="form-label">Alisverise Basla Buton Metni</label><input type="text" name="alisverise_basla_buton_metni" class="form-control" value="<?= esc(old('alisverise_basla_buton_metni', (string) ($config['alisverise_basla_buton_metni'] ?? ''))) ?>"></div></div></div></div>
                    </div>

                    <div class="d-grid"><button type="submit" class="btn btn-primary"><i class="ti ti-device-floppy me-1"></i> Cart Ayarlarini Kaydet</button></div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-xxl-7">
        <div class="card mb-4">
            <div class="card-header"><h5 class="mb-1">Mini Cart Onizlemesi</h5><p class="text-muted mb-0">Section siralari, uyari metinleri ve CTA etkisini sade cart akisi uzerinde gorun.</p></div>
            <div class="card-body">
                <?= view('admin/pages/partials/cart_preview', ['cartPreview' => $cartPreview ?? []]) ?>
            </div>
        </div>
    </div>
</div>
<?= $this->endSection() ?>
