<?= $this->extend('admin/layouts/main') ?>

<?= $this->section('content') ?>
<?php
$draftStatus = trim((string) ($draft['status'] ?? 'DRAFT'));
$config = is_array($checkoutConfig ?? null) ? $checkoutConfig : [];
$sections = is_array($config['sections'] ?? null) ? $config['sections'] : [];
?>

<div class="page-header">
    <div class="page-block">
        <div class="row">
            <div class="col-12"><div class="page-header-title"><h2 class="mb-0"><?= esc($page['name']) ?> Yonetimi</h2></div></div>
            <div class="col-12"><ul class="breadcrumb"><li class="breadcrumb-item"><a href="<?= site_url('admin/dashboard') ?>">Yonetim</a></li><li class="breadcrumb-item"><a href="<?= site_url('admin/pages') ?>">Sayfa Yonetimi</a></li><li class="breadcrumb-item" aria-current="page">Checkout Builder</li></ul></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card border-0 shadow-sm mb-4">
            <div class="card-body d-flex flex-wrap justify-content-between align-items-center gap-3">
                <div>
                    <div class="d-flex flex-wrap gap-2 mb-2"><span class="badge bg-light-primary"><?= esc($draftStatus) ?></span><span class="badge bg-light-secondary"><?= esc($page['code']) ?></span><span class="badge bg-light-success">Kontrollu Checkout Sablonu</span></div>
                    <h4 class="mb-1">Checkout Sayfa Sistemi</h4>
                    <p class="text-muted mb-0"><?= esc((string) ($builderPolicy['message'] ?? 'Checkout sayfasi tam serbest builder yerine kontrollu section mantigiyla yonetilir.')) ?></p>
                </div>
                <a href="<?= site_url('admin/pages/' . $page['code'] . '/drafts') ?>" class="btn btn-outline-primary">Draftlar</a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xxl-5">
        <div class="card mb-4">
            <div class="card-header"><h5 class="mb-1">Section Yonetimi</h5><p class="text-muted mb-0">Checkout akisini bozmadan metinleri, gorunurlugu ve sirayi yonetin.</p></div>
            <div class="card-body">
                <?php if (session()->getFlashdata('error')): ?><div class="alert alert-danger"><?= esc(session()->getFlashdata('error')) ?></div><?php endif; ?>
                <?php if (session()->getFlashdata('success')): ?><div class="alert alert-success"><?= esc(session()->getFlashdata('success')) ?></div><?php endif; ?>
                <form action="<?= site_url('admin/pages/checkout-builder/update') ?>" method="post">
                    <?= csrf_field() ?>
                    <input type="hidden" name="page_code" value="<?= esc($page['code']) ?>">
                    <input type="hidden" name="version_id" value="<?= esc($draft['id']) ?>">

                    <div class="accordion" id="checkoutSectionsAccordion">
                        <div class="accordion-item border rounded mb-3"><h2 class="accordion-header"><button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#checkoutTopArea">Sayfa Ust Alani</button></h2><div id="checkoutTopArea" class="accordion-collapse collapse show" data-bs-parent="#checkoutSectionsAccordion"><div class="accordion-body"><div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">Bolum Durumu</label><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="section_sayfa_ust_alani_active" value="1" <?= old('section_sayfa_ust_alani_active', ! empty($sections['sayfa_ust_alani']['active']) ? '1' : '') ? 'checked' : '' ?>><label class="form-check-label">Aktif</label></div></div><div class="col-md-6"><label class="form-label">Sira</label><input type="number" min="1" name="section_sayfa_ust_alani_order" class="form-control" value="<?= esc((string) old('section_sayfa_ust_alani_order', (string) ($sections['sayfa_ust_alani']['order'] ?? 1))) ?>"></div></div><div class="mb-3"><label class="form-label">Baslik</label><input type="text" name="sayfa_basligi" class="form-control" value="<?= esc(old('sayfa_basligi', (string) ($config['sayfa_basligi'] ?? ''))) ?>"></div><div class="mb-3"><label class="form-label">Alt Baslik</label><textarea name="sayfa_alt_basligi" rows="3" class="form-control"><?= esc(old('sayfa_alt_basligi', (string) ($config['sayfa_alt_basligi'] ?? ''))) ?></textarea></div><div class="row g-3"><div class="col-md-6"><div class="form-check"><input class="form-check-input" type="checkbox" name="breadcrumb_goster" value="1" <?= old('breadcrumb_goster', ! empty($config['breadcrumb_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Breadcrumb goster</label></div></div><div class="col-md-6"><label class="form-label">Guven Kisa Notu</label><input type="text" name="guven_kisa_notu" class="form-control" value="<?= esc(old('guven_kisa_notu', (string) ($config['guven_kisa_notu'] ?? ''))) ?>"></div></div></div></div></div>

                        <div class="accordion-item border rounded mb-3"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#checkoutStepsArea">Adim Cubugu</button></h2><div id="checkoutStepsArea" class="accordion-collapse collapse" data-bs-parent="#checkoutSectionsAccordion"><div class="accordion-body"><div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">Bolum Durumu</label><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="section_adim_cubugu_active" value="1" <?= old('section_adim_cubugu_active', ! empty($sections['adim_cubugu']['active']) ? '1' : '') ? 'checked' : '' ?>><label class="form-check-label">Aktif</label></div></div><div class="col-md-6"><label class="form-label">Sira</label><input type="number" min="1" name="section_adim_cubugu_order" class="form-control" value="<?= esc((string) old('section_adim_cubugu_order', (string) ($sections['adim_cubugu']['order'] ?? 2))) ?>"></div></div><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="adim_cubugu_gorunur" value="1" <?= old('adim_cubugu_gorunur', ! empty($config['adim_cubugu_gorunur'])) ? 'checked' : '' ?>><label class="form-check-label">Adim cubugunu goster</label></div><div class="mb-0"><label class="form-label">Yardimci Metin</label><textarea name="adim_cubugu_aciklama" rows="3" class="form-control"><?= esc(old('adim_cubugu_aciklama', (string) ($config['adim_cubugu_aciklama'] ?? ''))) ?></textarea></div></div></div></div>

                        <div class="accordion-item border rounded mb-3"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#checkoutAddressArea">Teslimat / Fatura Bilgileri</button></h2><div id="checkoutAddressArea" class="accordion-collapse collapse" data-bs-parent="#checkoutSectionsAccordion"><div class="accordion-body"><div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">Bolum Durumu</label><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="section_teslimat_fatura_alani_active" value="1" <?= old('section_teslimat_fatura_alani_active', ! empty($sections['teslimat_fatura_alani']['active']) ? '1' : '') ? 'checked' : '' ?>><label class="form-check-label">Aktif</label></div></div><div class="col-md-6"><label class="form-label">Sira</label><input type="number" min="1" name="section_teslimat_fatura_alani_order" class="form-control" value="<?= esc((string) old('section_teslimat_fatura_alani_order', (string) ($sections['teslimat_fatura_alani']['order'] ?? 3))) ?>"></div></div><div class="mb-3"><label class="form-label">Bolum Basligi</label><input type="text" name="teslimat_baslik" class="form-control" value="<?= esc(old('teslimat_baslik', (string) ($config['teslimat_baslik'] ?? ''))) ?>"></div><div class="mb-3"><label class="form-label">Aciklama</label><textarea name="teslimat_aciklama" rows="3" class="form-control"><?= esc(old('teslimat_aciklama', (string) ($config['teslimat_aciklama'] ?? ''))) ?></textarea></div><div class="mb-3"><label class="form-label">Ayni Adres Notu</label><input type="text" name="ayni_adres_notu" class="form-control" value="<?= esc(old('ayni_adres_notu', (string) ($config['ayni_adres_notu'] ?? ''))) ?>"></div><div class="mb-0"><label class="form-label">Zorunlu Alan Bilgisi</label><input type="text" name="zorunlu_alan_bilgi_metni" class="form-control" value="<?= esc(old('zorunlu_alan_bilgi_metni', (string) ($config['zorunlu_alan_bilgi_metni'] ?? ''))) ?>"></div></div></div></div>

                        <div class="accordion-item border rounded mb-3"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#checkoutPaymentArea">Odeme Yontemi</button></h2><div id="checkoutPaymentArea" class="accordion-collapse collapse" data-bs-parent="#checkoutSectionsAccordion"><div class="accordion-body"><div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">Bolum Durumu</label><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="section_odeme_yontemi_alani_active" value="1" <?= old('section_odeme_yontemi_alani_active', ! empty($sections['odeme_yontemi_alani']['active']) ? '1' : '') ? 'checked' : '' ?>><label class="form-check-label">Aktif</label></div></div><div class="col-md-6"><label class="form-label">Sira</label><input type="number" min="1" name="section_odeme_yontemi_alani_order" class="form-control" value="<?= esc((string) old('section_odeme_yontemi_alani_order', (string) ($sections['odeme_yontemi_alani']['order'] ?? 4))) ?>"></div></div><div class="mb-3"><label class="form-label">Bolum Basligi</label><input type="text" name="odeme_baslik" class="form-control" value="<?= esc(old('odeme_baslik', (string) ($config['odeme_baslik'] ?? ''))) ?>"></div><div class="mb-3"><label class="form-label">Aciklama</label><textarea name="odeme_aciklama" rows="3" class="form-control"><?= esc(old('odeme_aciklama', (string) ($config['odeme_aciklama'] ?? ''))) ?></textarea></div><div class="mb-3"><label class="form-label">Guvenli Odeme Notu</label><input type="text" name="guvenli_odeme_notu" class="form-control" value="<?= esc(old('guvenli_odeme_notu', (string) ($config['guvenli_odeme_notu'] ?? ''))) ?>"></div><div class="row g-2"><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="kart_logo_goster" value="1" <?= old('kart_logo_goster', ! empty($config['kart_logo_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Kart logolarini goster</label></div></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="guven_rozeti_goster" value="1" <?= old('guven_rozeti_goster', ! empty($config['guven_rozeti_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Guven rozetini goster</label></div></div></div></div></div></div>

                        <div class="accordion-item border rounded mb-3"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#checkoutSummaryArea">Siparis Ozeti</button></h2><div id="checkoutSummaryArea" class="accordion-collapse collapse" data-bs-parent="#checkoutSectionsAccordion"><div class="accordion-body"><div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">Bolum Durumu</label><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="section_siparis_ozeti_alani_active" value="1" <?= old('section_siparis_ozeti_alani_active', ! empty($sections['siparis_ozeti_alani']['active']) ? '1' : '') ? 'checked' : '' ?>><label class="form-check-label">Aktif</label></div></div><div class="col-md-6"><label class="form-label">Sira</label><input type="number" min="1" name="section_siparis_ozeti_alani_order" class="form-control" value="<?= esc((string) old('section_siparis_ozeti_alani_order', (string) ($sections['siparis_ozeti_alani']['order'] ?? 5))) ?>"></div></div><div class="mb-3"><label class="form-label">Baslik</label><input type="text" name="ozet_baslik" class="form-control" value="<?= esc(old('ozet_baslik', (string) ($config['ozet_baslik'] ?? ''))) ?>"></div><div class="row g-2 mb-3"><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="kupon_alani_goster" value="1" <?= old('kupon_alani_goster', ! empty($config['kupon_alani_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Kupon alanini goster</label></div></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="indirim_satiri_goster" value="1" <?= old('indirim_satiri_goster', ! empty($config['indirim_satiri_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Indirim satirini goster</label></div></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="kargo_satiri_goster" value="1" <?= old('kargo_satiri_goster', ! empty($config['kargo_satiri_goster'])) ? 'checked' : '' ?>><label class="form-check-label">Kargo satirini goster</label></div></div></div><div class="mb-0"><label class="form-label">Siparis Tipi Notu</label><textarea name="siparis_tipi_notu" rows="3" class="form-control"><?= esc(old('siparis_tipi_notu', (string) ($config['siparis_tipi_notu'] ?? ''))) ?></textarea></div></div></div></div>

                        <div class="accordion-item border rounded mb-4"><h2 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#checkoutInfoArea">Bilgilendirme / Guven / CTA</button></h2><div id="checkoutInfoArea" class="accordion-collapse collapse" data-bs-parent="#checkoutSectionsAccordion"><div class="accordion-body"><div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">Bolum Durumu</label><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="section_bilgilendirme_guven_cta_alani_active" value="1" <?= old('section_bilgilendirme_guven_cta_alani_active', ! empty($sections['bilgilendirme_guven_cta_alani']['active']) ? '1' : '') ? 'checked' : '' ?>><label class="form-check-label">Aktif</label></div></div><div class="col-md-6"><label class="form-label">Sira</label><input type="number" min="1" name="section_bilgilendirme_guven_cta_alani_order" class="form-control" value="<?= esc((string) old('section_bilgilendirme_guven_cta_alani_order', (string) ($sections['bilgilendirme_guven_cta_alani']['order'] ?? 6))) ?>"></div></div><div class="mb-3"><label class="form-label">Bilgi Kutusu Basligi</label><input type="text" name="bilgi_kutusu_baslik" class="form-control" value="<?= esc(old('bilgi_kutusu_baslik', (string) ($config['bilgi_kutusu_baslik'] ?? ''))) ?>"></div><div class="mb-3"><label class="form-label">Aciklama</label><textarea name="bilgi_kutusu_aciklama" rows="3" class="form-control"><?= esc(old('bilgi_kutusu_aciklama', (string) ($config['bilgi_kutusu_aciklama'] ?? ''))) ?></textarea></div><div class="mb-3"><label class="form-label">Guven Mesaji</label><input type="text" name="guven_mesaji" class="form-control" value="<?= esc(old('guven_mesaji', (string) ($config['guven_mesaji'] ?? ''))) ?>"></div><div class="mb-3"><label class="form-label">Siparisi Tamamla Buton Metni</label><input type="text" name="tamamla_buton_metni" class="form-control" value="<?= esc(old('tamamla_buton_metni', (string) ($config['tamamla_buton_metni'] ?? ''))) ?>"></div><div class="mb-0"><label class="form-label">Alt Yardim Metni</label><textarea name="alt_yardim_metni" rows="3" class="form-control"><?= esc(old('alt_yardim_metni', (string) ($config['alt_yardim_metni'] ?? ''))) ?></textarea></div></div></div></div>
                    </div>

                    <div class="d-grid"><button type="submit" class="btn btn-primary"><i class="ti ti-device-floppy me-1"></i> Checkout Ayarlarini Kaydet</button></div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-xxl-7">
        <div class="card mb-4">
            <div class="card-header"><h5 class="mb-1">Mini Checkout Onizlemesi</h5><p class="text-muted mb-0">Section siralari ve yardimci metinlerin sade checkout akisina etkisini gorun.</p></div>
            <div class="card-body">
                <?= view('admin/pages/partials/checkout_preview', ['checkoutPreview' => $checkoutPreview ?? []]) ?>
            </div>
        </div>
    </div>
</div>
<?= $this->endSection() ?>
