<?php
$preview = is_array($productDetailPreview ?? null) ? $productDetailPreview : [];
$config = is_array($preview['config'] ?? null) ? $preview['config'] : [];
$sections = is_array($preview['sections'] ?? null) ? $preview['sections'] : [];
$product = is_array($preview['product'] ?? null) ? $preview['product'] : [];
$hasVisibleSections = ! empty($preview['hasVisibleSections']);
$visibleSectionCount = (int) ($preview['visibleSectionCount'] ?? 0);
?>

<div class="card border shadow-none bg-light mb-3">
    <div class="card-body">
        <div class="d-flex flex-wrap justify-content-between align-items-center gap-2">
            <div>
                <div class="fw-semibold mb-1">Product Detail Mini Preview</div>
                <div class="small text-muted">Urun tanitimi, fiyat, meta bilgi ve yorum ozetini sade yonetici gorunumuyle izleyin.</div>
            </div>
            <span class="badge bg-light-primary"><?= esc((string) $visibleSectionCount) ?> aktif bolum</span>
        </div>
    </div>
</div>

<?php if (! $hasVisibleSections): ?>
    <div class="alert alert-light border mb-3">
        <div class="fw-semibold mb-1">Preview hazir</div>
        <div class="small text-muted">Tum bolumler pasif olsa bile product detail akisinin bos kalmamasi icin fallback durum gosterilir.</div>
    </div>
<?php endif; ?>

<?php if (! empty($config['breadcrumb_goster']) && ! empty($config['sections']['sayfa_ust_alani']['active'])): ?>
    <div class="small text-muted mb-3">Anasayfa / Kategori / <?= esc((string) ($product['name'] ?? 'Urun')) ?></div>
<?php endif; ?>

<?php foreach ($sections as $section): ?>
    <?php if (! ($section['active'] ?? false)) {
        continue;
    } ?>
    <?php if (($section['key'] ?? '') === 'sayfa_ust_alani'): ?>
        <div class="card border shadow-none mb-3"><div class="card-body"><div class="d-flex flex-wrap justify-content-between gap-3"><div><span class="badge bg-light-primary mb-2"><?= esc((string) ($config['bilgi_kampanya_rozeti_metni'] ?? 'Editorun Secimi')) ?></span><h4 class="mb-1"><?= esc((string) ($config['sayfa_basligi'] ?? 'Urun Detayi')) ?></h4><p class="text-muted mb-2"><?= esc((string) ($config['sayfa_alt_basligi'] ?? 'Urunun tum detaylarini, fiyat bilgisini ve satin alma alanini yonetin.')) ?></p><div class="small text-muted"><?= esc((string) ($config['kisa_aciklama'] ?? 'Tanitim, fiyat ve guven notlari ayni sayfada dengeli bir bicimde sunulur.')) ?></div></div><span class="badge bg-light-secondary">Sira <?= esc((string) ($section['order'] ?? 1)) ?></span></div></div></div>
    <?php elseif (($section['key'] ?? '') === 'urun_ana_tanitim_alani'): ?>
        <div class="card border shadow-none mb-3"><div class="card-body"><div class="row g-3 align-items-start"><div class="col-lg-4"><?php if (! empty($config['kapak_galeri_goster'])): ?><div class="rounded bg-light d-flex align-items-center justify-content-center mb-2" style="height:220px;"><i class="ti ti-book-2 fs-1 text-muted"></i></div><div class="d-flex gap-2"><?php for ($i = 0; $i < 3; $i++): ?><div class="border rounded bg-light flex-fill" style="height:48px;"></div><?php endfor; ?></div><?php endif; ?></div><div class="col-lg-8"><div class="fw-semibold mb-1"><?= esc((string) ($product['name'] ?? 'BeAble Pro Ileri Seviye Calisma Kitabi')) ?></div><div class="small text-muted mb-2"><?= esc((string) ($config['urun_tanitim_kisa_aciklama'] ?? 'Kapak, format, yazar ve hizli satin alma aksiyonlarini bir arada sunun.')) ?></div><div class="d-flex flex-wrap gap-2 mb-3"><?php if (! empty($config['format_etiketi_goster'])): ?><span class="badge bg-light-secondary"><?= esc((string) ($product['format'] ?? 'Basili + Dijital')) ?></span><?php endif; ?><?php if (! empty($config['yazar_bilgisi_goster'])): ?><span class="badge bg-light-primary">Yazar: <?= esc((string) ($product['author'] ?? 'Hilal Y.')) ?></span><?php endif; ?></div><div class="d-flex flex-wrap gap-2"><?php if (! empty($config['favori_butonu_goster'])): ?><button type="button" class="btn btn-outline-secondary btn-sm disabled">Favorile</button><?php endif; ?><button type="button" class="btn btn-primary btn-sm disabled"><?= esc((string) ($config['sepete_ekle_buton_metni'] ?? 'Sepete Ekle')) ?></button></div></div></div></div></div>
    <?php elseif (($section['key'] ?? '') === 'fiyat_satin_alma_bilgi_alani'): ?>
        <div class="card border shadow-none mb-3"><div class="card-body"><div class="fw-semibold mb-1"><?= esc((string) ($config['fiyat_satin_alma_baslik'] ?? 'Fiyat ve Satin Alma Bilgisi')) ?></div><div class="small text-muted mb-3"><?= esc((string) ($config['fiyat_satin_alma_aciklama'] ?? 'Kullaniciya fiyat, stok ve teslimat notlarini guven veren bir alanda gosterin.')) ?></div><div class="d-flex flex-wrap align-items-center gap-3 mb-3"><?php if (! empty($config['eski_fiyat_goster'])): ?><span class="text-muted text-decoration-line-through"><?= esc(number_format((float) ($product['old_price'] ?? 399.90), 2, ',', '.')) ?> TL</span><?php endif; ?><span class="fs-4 fw-bold"><?= esc(number_format((float) ($product['price'] ?? 349.90), 2, ',', '.')) ?> TL</span><?php if (! empty($config['indirim_rozeti_goster'])): ?><span class="badge bg-light-success">%<?= esc((string) ($product['discount_rate'] ?? 12)) ?> indirim</span><?php endif; ?></div><?php if (! empty($config['stok_uygunluk_bilgisi_goster'])): ?><div class="alert alert-light border mb-3"><?= esc((string) ($product['stock_message'] ?? 'Stokta var')) ?></div><?php endif; ?><div class="small text-muted mb-2"><?= esc((string) ($config['dijital_erisim_kisa_notu'] ?? 'Dijital urunlerde erisim satin alma sonrasi e-posta ile iletilir.')) ?></div><div class="small text-muted mb-2"><?= esc((string) ($config['teslimat_kargo_kisa_notu'] ?? 'Basili urunlerde hazirlama ve kargo bilgisi siparis adiminda netlesir.')) ?></div><div class="small text-success"><?= esc((string) ($config['guvenli_alisveris_kisa_notu'] ?? 'Guvenli alisveris ve onayli odeme altyapisi ile korunur.')) ?></div></div></div>
    <?php elseif (($section['key'] ?? '') === 'urun_meta_bilgi_alani'): ?>
        <div class="card border shadow-none mb-3"><div class="card-body"><div class="fw-semibold mb-3"><?= esc((string) ($config['urun_meta_bilgi_baslik'] ?? 'Urun Meta Bilgileri')) ?></div><div class="row g-2"><?php if (! empty($config['isbn_goster'])): ?><div class="col-md-6"><div class="border rounded p-2 small">ISBN: <?= esc((string) ($product['isbn'] ?? '978-625-0000-12-3')) ?></div></div><?php endif; ?><?php if (! empty($config['dil_goster'])): ?><div class="col-md-6"><div class="border rounded p-2 small">Dil: <?= esc((string) ($product['language'] ?? 'Turkce')) ?></div></div><?php endif; ?><?php if (! empty($config['sayfa_sayisi_goster'])): ?><div class="col-md-6"><div class="border rounded p-2 small">Sayfa: <?= esc((string) ($product['page_count'] ?? '240')) ?></div></div><?php endif; ?><?php if (! empty($config['yayin_yili_goster'])): ?><div class="col-md-6"><div class="border rounded p-2 small">Yayin Yili: <?= esc((string) ($product['publish_year'] ?? '2026')) ?></div></div><?php endif; ?><?php if (! empty($config['format_goster'])): ?><div class="col-md-6"><div class="border rounded p-2 small">Format: <?= esc((string) ($product['format'] ?? 'Basili + Dijital')) ?></div></div><?php endif; ?><?php if (! empty($config['kategori_etiket_goster'])): ?><div class="col-md-6"><div class="border rounded p-2 small">Kategori / Etiket: <?= esc((string) ($product['category'] ?? 'Egitim')) ?>, <?= esc((string) ($product['tags'] ?? 'Sinav, Gelisim')) ?></div></div><?php endif; ?></div></div></div>
    <?php elseif (($section['key'] ?? '') === 'aciklama_icerik_alani'): ?>
        <div class="card border shadow-none mb-3"><div class="card-body"><div class="fw-semibold mb-3"><?= esc((string) ($config['aciklama_icerik_baslik'] ?? 'Aciklama ve Icerik')) ?></div><div class="mb-3"><div class="fw-semibold small mb-1"><?= esc((string) ($config['uzun_aciklama_basligi'] ?? 'Urun Aciklamasi')) ?></div><div class="small text-muted">Bu preview alani, uzun icerik ve urun hikayesinin yerlesimini orneklemek icin kullanilir.</div></div><div class="mb-3"><div class="fw-semibold small mb-1"><?= esc((string) ($config['arka_kapak_tanitim_basligi'] ?? 'Arka Kapak / Tanitim')) ?></div><div class="small text-muted">Arka kapak akisi veya tanitim metni bu alanda ozetlenir.</div></div><div class="mb-3"><div class="fw-semibold small mb-1"><?= esc((string) ($config['one_cikanlar_basligi'] ?? 'One Cikanlar')) ?></div><ul class="small text-muted mb-0"><li>Planli calisma akisi</li><li>Kademeli zorluk seviyesi</li><li>Dijital destek icerigi</li></ul></div><div class="small text-muted"><?= esc((string) ($config['icerik_aciklama_notu'] ?? 'Bu alan urunun neden tercih edilmesi gerektigini ozetler.')) ?></div></div></div>
    <?php elseif (($section['key'] ?? '') === 'yorum_puan_alani'): ?>
        <div class="card border shadow-none mb-3"><div class="card-body"><div class="fw-semibold mb-1"><?= esc((string) ($config['yorum_puan_baslik'] ?? 'Yorumlar ve Puanlar')) ?></div><div class="small text-muted mb-3"><?= esc((string) ($config['yorum_ozeti_metni'] ?? 'Kullanicilarin geri bildirimleri satin alma kararini destekler.')) ?></div><div class="d-flex flex-wrap gap-3 align-items-center mb-3"><?php if (! empty($config['puan_ortalamasi_goster'])): ?><div class="fs-5 fw-bold"><?= esc(number_format((float) ($product['rating'] ?? 4.8), 1, ',', '.')) ?>/5</div><?php endif; ?><?php if (! empty($config['yorum_sayisi_goster'])): ?><div class="small text-muted"><?= esc((string) ($product['review_count'] ?? 126)) ?> yorum</div><?php endif; ?></div><div class="small text-primary"><?= esc((string) ($config['yorum_yap_cagrisi_metni'] ?? 'Deneyimini paylas ve diger kullanicilara yol goster.')) ?></div></div></div>
    <?php elseif (($section['key'] ?? '') === 'ilgili_urunler_cta_alani'): ?>
        <div class="card border shadow-none mb-0"><div class="card-body"><div class="fw-semibold mb-1"><?= esc((string) ($config['ilgili_urunler_cta_baslik'] ?? 'Ilgili Urunler ve CTA')) ?></div><div class="small text-muted mb-3"><?= esc((string) ($config['ilgili_urunler_cta_aciklama'] ?? 'Benzer urunler ve ek aksiyon alaniyla kesfetme akisini guclendir.')) ?></div><div class="fw-semibold small mb-2"><?= esc((string) ($config['benzer_urunler_basligi'] ?? 'Benzer Urunler')) ?></div><div class="row g-2 mb-3"><?php for ($i = 0; $i < 3; $i++): ?><div class="col-md-4"><div class="border rounded p-3 bg-light h-100"><div class="small fw-semibold mb-1">BeAble Pro Seri <?= esc((string) ($i + 2)) ?></div><div class="small text-muted">Benzer urun karti preview alani</div></div></div><?php endfor; ?></div><div class="d-flex flex-wrap justify-content-between align-items-center gap-3"><div class="small text-success"><?= esc((string) ($config['guven_notu_kisa_bilgi'] ?? 'Iade, destek ve satin alma guvencesi tek ekranda gorunur.')) ?></div><button type="button" class="btn btn-outline-primary btn-sm disabled"><?= esc((string) ($config['cta_buton_metni'] ?? 'Hemen Incele')) ?></button></div></div></div>
    <?php endif; ?>
<?php endforeach; ?>
